<!doctype html><html><head><meta charset="utf-8"><style>
body{font-family:DejaVu Sans,sans-serif;font-size:11px;color:#17202a}.header{display:table;width:100%;border-bottom:3px solid {{ $settings['primary_color'] ?? '#0f766e' }};padding-bottom:10px;margin-bottom:16px}.logo{display:table-cell;width:85px}.logo img{max-width:75px;max-height:70px}.company{display:table-cell;vertical-align:top}.system-name{font-size:18px;font-weight:bold}.muted{color:#59666c}.title{font-size:17px;margin:14px 0 8px}.info,.table{width:100%;border-collapse:collapse}.info td,.table th,.table td{border:1px solid #d7dee2;padding:6px}.table th{background:#eef3f4}.metrics{display:table;width:100%;margin:12px 0}.metric{display:table-cell;border:1px solid #d7dee2;padding:8px}.footer{border-top:1px solid #ddd;margin-top:18px;padding-top:8px;text-align:center;color:#555}
</style></head><body>
@include('pdf.partials.client-header')
<h1 class="title">Ficha del cliente</h1>
<table class="info"><tr><td><strong>Nombre</strong></td><td>{{ $cliente->nombre }}</td><td><strong>Documento</strong></td><td>{{ $cliente->documento }}</td></tr><tr><td><strong>Telefono</strong></td><td>{{ $cliente->telefono }}</td><td><strong>Email</strong></td><td>{{ $cliente->email }}</td></tr><tr><td><strong>Direccion</strong></td><td>{{ $cliente->direccion }}</td><td><strong>Urbanizacion</strong></td><td>{{ $cliente->urbanizacion?->nombre }}</td></tr><tr><td><strong>Registrado por</strong></td><td>{{ $cliente->createdBy?->name ?? 'Usuario no registrado' }}</td><td><strong>Fecha registro</strong></td><td>{{ $cliente->created_at?->format('d/m/Y H:i') }}</td></tr></table>
<div class="metrics"><div class="metric"><strong>Total vendido</strong><br>{{ number_format($resumen['total_vendido'], 2) }}</div><div class="metric"><strong>Total pagado</strong><br>{{ number_format($resumen['total_pagado'], 2) }}</div><div class="metric"><strong>Total pendiente</strong><br>{{ number_format($resumen['total_pendiente'], 2) }}</div></div>
<h2 class="title">Reservas</h2><table class="table"><thead><tr><th>Lote</th><th>Estado</th><th>Fecha</th><th>Vencimiento</th><th>Monto</th></tr></thead><tbody>@forelse($cliente->reservas as $reserva)<tr><td>{{ $reserva->lote->manzano->codigo }}-{{ $reserva->lote->codigo }}</td><td>{{ $reserva->estado }}</td><td>{{ $reserva->fecha_reserva?->format('d/m/Y') }}</td><td>{{ $reserva->fecha_vencimiento?->format('d/m/Y') }}</td><td>{{ number_format($reserva->monto_reserva, 2) }}</td></tr>@empty<tr><td colspan="5">Sin reservas.</td></tr>@endforelse</tbody></table>
<h2 class="title">Ventas</h2><table class="table"><thead><tr><th>Lote</th><th>Fecha</th><th>Precio</th><th>Estado</th><th>Saldo cuotas</th></tr></thead><tbody>@forelse($cliente->ventas as $venta)<tr><td>{{ $venta->lote->manzano->codigo }}-{{ $venta->lote->codigo }}</td><td>{{ $venta->fecha_venta?->format('d/m/Y') }}</td><td>{{ number_format($venta->precio_final, 2) }}</td><td>{{ $venta->estado }}</td><td>{{ number_format($venta->cuotas->sum('saldo_pendiente'), 2) }}</td></tr>@empty<tr><td colspan="5">Sin ventas.</td></tr>@endforelse</tbody></table>
<div class="footer">{{ $settings['footer_text'] ?? '' }}</div></body></html>
