@extends('layouts.app')
@section('content')
<div class="topbar"><div><h1 class="title">{{ $grupo->nombre }}</h1><div class="breadcrumb">Equipo comercial &gt; Grupos comerciales &gt; Detalle</div></div><div class="actions">@if(auth()->user()->hasRole('super administrador'))<a class="btn" href="{{ route('grupos-comerciales.asignaciones', $grupo) }}">Asignar urbanizaciones</a>@endif<a class="btn secondary" href="{{ route('grupos-comerciales.index') }}">Volver</a></div></div>
@if(session('status'))<div class="status">{{ session('status') }}</div>@endif
<div class="card"><h2>Datos generales</h2><p><strong>Supervisor comercial:</strong> {{ $grupo->supervisor?->name ?? 'Sin responsable' }}</p><p><strong>Estado:</strong> {{ $grupo->activo ? 'Activo' : 'Inactivo' }}</p><p>{{ $grupo->descripcion }}</p><p class="muted">{{ $grupo->observaciones }}</p></div>
<div class="grid stats">@foreach(['Terrenos vendidos'=>$metricas['vendidos'],'Reservas activas'=>$metricas['reservas'],'Ventas contado'=>$metricas['contado'],'Ventas crédito'=>$metricas['credito'],'Monto vendido'=>number_format($metricas['monto'],2)] as $label=>$value)<div class="card metric"><span class="muted">{{ $label }}</span><div class="stat-value">{{ $value }}</div></div>@endforeach</div>
<div class="grid dashboard-grid"><div class="card"><h2>Urbanizaciones asignadas</h2>@forelse($grupo->urbanizaciones as $item)<p>{{ $item->nombre }} <span class="badge activa">activa</span></p>@empty<p>Sin urbanizaciones asignadas.</p>@endforelse</div><div class="card"><h2>Equipo</h2><p><strong>Supervisores / responsables:</strong> {{ $grupo->usuarios->whereIn('pivot.tipo',['supervisor_comercial','supervisor_ventas'])->count() }}</p><p><strong>Vendedores:</strong> {{ $grupo->asesores->count() }}</p>@foreach($grupo->asesores as $asesor)<p>{{ $asesor->user?->name }}</p>@endforeach</div></div>
<h2>Ventas recientes</h2><div class="table-scroll"><table class="table"><thead><tr><th>Fecha</th><th>Urbanización</th><th>Cliente</th><th>Lote</th><th>Vendedor</th><th>Monto</th></tr></thead><tbody>@forelse($grupo->ventas as $venta)<tr><td>{{ $venta->fecha_venta?->format('d/m/Y') }}</td><td>{{ $venta->lote->manzano->urbanizacion->nombre }}</td><td>{{ $venta->cliente->nombre }}</td><td>{{ $venta->lote->manzano->codigo }}-{{ $venta->lote->codigo }}</td><td>{{ $venta->vendedor?->name ?? '-' }}</td><td>{{ number_format($venta->monto_total,2) }}</td></tr>@empty<tr><td colspan="6">Sin ventas recientes.</td></tr>@endforelse</tbody></table></div>
<h2>Reservas activas</h2><div class="table-scroll"><table class="table"><thead><tr><th>Fecha</th><th>Cliente</th><th>Lote</th><th>Vendedor</th><th>Vencimiento</th></tr></thead><tbody>@forelse($grupo->reservas as $reserva)<tr><td>{{ $reserva->fecha_reserva?->format('d/m/Y') }}</td><td>{{ $reserva->cliente->nombre }}</td><td>{{ $reserva->lote->manzano->codigo }}-{{ $reserva->lote->codigo }}</td><td>{{ $reserva->vendedor?->name ?? '-' }}</td><td>{{ $reserva->fecha_vencimiento?->format('d/m/Y') }}</td></tr>@empty<tr><td colspan="5">Sin reservas activas.</td></tr>@endforelse</tbody></table></div>
@endsection
